server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用为服务名进行路由。
      routes: # 可以为controller中的所有rest接口做路由
        - id: payment_routh           # 路由id：payment_route，没有固定规则，建议配合服务名
#          uri: http://localhost:8001  # 匹配后提供服务的路由地址
          uri: lb://SERVICEPROVIDER  # lb://开头代表从注册中心中获取服务，后面接的就是你需要转发到的服务名称
          predicates:
            - Path=/payment/getPaymentById/**    # 断言：路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://SERVICEPROVIDER  # lb://开头代表从注册中心中获取服务，后面接的就是你需要转发到的服务名称
          predicates:
            - Path=/payment/lb/**

        - id: payment_routh3
          uri: https://www.zhihu.com/
          predicates:
              - Path=/zhihu
#              - After=2021-09-18T00:00:00+08:00[Asia/Shanghai]
eureka:
  instance:
    hostname: cloud-gateway-service
    prefer-ip-address: true
    instance-id: cloud-gateway9527
  client:
    service-url:
      register-with-eureka: true
      fetch-register: true
      defaultZone: http://eureka7001.com:7001/eureka
