# 微服务端口号
server:
  port: 8001

# 微服务名称
spring:
  application:
    name: serviceProvider

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver     # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: password


mybatis:
  mapper-locations: classpath:mapper/*.xml  # 扫描类路径下mapper文件夹下的.xml配置文件
  type-aliases-package: com.cxs.springbootWork.entity  # 该包所有Entity类，取默认别名

eureka:
  client:
    # 表示将自己注册进EurekaServer默认为true
    register-with-eureka: true
    # 表示可以从Eureka抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: serviceProvider8001
    prefer-ip-address: true