# 微服务端口号
server:
  port: 8001

# 微服务名称
spring:
  application:
    name: cloud-payment-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      # 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver     # mysql驱动包
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: password


mybatis:
  mapper-locations: classpath:mapper/*.xml  # 扫描类路径下mapper文件夹下的.xml配置文件
  type-aliases-package: com.cxs.payment.entity  # 该包所有Entity类，取默认别名